import jsPDF from "jspdf";
import { PerformanceScores } from "@/hooks/use-performance";

export function generateRecommendationPDF(
  scores: PerformanceScores,
  totalPoints: number,
  totalSessions: number
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFontSize(24);
  doc.setTextColor(41, 98, 255);
  doc.text("InterviewLens", pageWidth / 2, y, { align: "center" });
  y += 10;

  doc.setFontSize(16);
  doc.setTextColor(40, 40, 40);
  doc.text("Letter of Recommendation", pageWidth / 2, y, { align: "center" });
  y += 15;

  // Line
  doc.setDrawColor(200, 200, 200);
  doc.line(20, y, pageWidth - 20, y);
  y += 15;

  // Date
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text(`Date: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, 20, y);
  y += 15;

  // Body
  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);

  const level =
    totalPoints >= 500 ? "Expert" :
    totalPoints >= 300 ? "Advanced" :
    totalPoints >= 150 ? "Intermediate" : "Beginner";

  const body = `To Whom It May Concern,

This letter is generated by InterviewLens, an AI-powered technical interview platform, to recognize the performance of the candidate across ${totalSessions} interview session(s).

The candidate has demonstrated consistent performance and earned a total of ${totalPoints} points, achieving the "${level}" level on our platform.

Performance Summary:
• Problem Solving: ${scores.problemSolving}/10
• Pressure Handling: ${scores.pressureHandling}/10
• Creative Thinking: ${scores.creativeThinking}/10
• Time Management: ${scores.timeManagement}/10
• Communication: ${scores.communication}/10
• Technical Skills: ${scores.technicalSkills}/10
• Overall Score: ${scores.overallScore}/10

${scores.strengths.length > 0 ? `Key Strengths:\n${scores.strengths.map((s) => `• ${s}`).join("\n")}` : ""}

Based on the above assessment, the candidate has shown strong aptitude in technical interviews and is recommended for further consideration.

This is an AI-generated assessment and should be used as a supplementary reference.

Best regards,
InterviewLens AI Assessment System`;

  const lines = doc.splitTextToSize(body, pageWidth - 40);
  doc.text(lines, 20, y);

  doc.save("InterviewLens_Recommendation.pdf");
}
